import type { Product } from "@/context/CartContext";

export const categories = [
  "All",
  "Handmade Clothing",
  "Beauty/Skincare",
  "Bags & Wallets",
  "Accessories",
  "Stickers",
  "Ceramics & Stoneware",
] as const;

export const products: Product[] = [
  {
    id: "p1",
    name: "Linen Wrap Dress",
    price: 180,
    category: "Handmade Clothing",
    image: "https://picsum.photos/seed/moderncircle21/800/600",
    inStock: true,
    description: "Hand-stitched linen wrap dress in natural beige.",
  },
  {
    id: "p2",
    name: "Embroidered Cotton Top",
    price: 95,
    category: "Handmade Clothing",
    image: "https://picsum.photos/seed/moderncircle22/800/600",
    inStock: false,
    description: "Lightweight cotton blouse with hand embroidery.",
  },
  {
    id: "p3",
    name: "Rose Clay Face Mask",
    price: 45,
    category: "Beauty/Skincare",
    image: "https://picsum.photos/seed/moderncircle23/800/600",
    inStock: true,
    description: "Gentle clay mask with rose and chamomile.",
  },
  {
    id: "p4",
    name: "Argan Body Oil",
    price: 60,
    category: "Beauty/Skincare",
    image: "https://picsum.photos/seed/moderncircle24/800/600",
    inStock: true,
    description: "Cold-pressed argan oil with neroli.",
  },
  {
    id: "p5",
    name: "Leather Crossbody Bag",
    price: 240,
    category: "Bags & Wallets",
    image: "https://picsum.photos/seed/moderncircle25/800/600",
    inStock: true,
    description: "Vegetable-tanned leather, handcrafted in Tunis.",
  },
  {
    id: "p6",
    name: "Card Wallet",
    price: 75,
    category: "Bags & Wallets",
    image: "https://picsum.photos/seed/moderncircle26/800/600",
    inStock: true,
    description: "Slim card holder with hand-stitched edges.",
  },
  {
    id: "p7",
    name: "Brass Hoop Earrings",
    price: 55,
    category: "Accessories",
    image: "https://picsum.photos/seed/moderncircle27/800/600",
    inStock: true,
    description: "Hammered brass hoops, hypoallergenic posts.",
  },
  {
    id: "p8",
    name: "Silk Hair Scrunchie Set",
    price: 35,
    category: "Accessories",
    image: "https://picsum.photos/seed/moderncircle28/800/600",
    inStock: false,
    description: "Set of three mulberry silk scrunchies.",
  },
  {
    id: "p9",
    name: "Botanical Sticker Pack",
    price: 18,
    category: "Stickers",
    image: "https://picsum.photos/seed/moderncircle29/800/600",
    inStock: true,
    description: "Twelve waterproof vinyl stickers, plant illustrations.",
  },
  {
    id: "p10",
    name: "Coffee Lover Stickers",
    price: 15,
    category: "Stickers",
    image: "https://picsum.photos/seed/moderncircle30/800/600",
    inStock: true,
    description: "Six matte stickers for journals & laptops.",
  },
  {
    id: "p11",
    name: "Stoneware Mug",
    price: 50,
    category: "Ceramics & Stoneware",
    image: "https://picsum.photos/seed/moderncircle31/800/600",
    inStock: true,
    description: "Wheel-thrown stoneware mug, matte glaze.",
  },
  {
    id: "p12",
    name: "Ceramic Serving Bowl",
    price: 110,
    category: "Ceramics & Stoneware",
    image: "https://picsum.photos/seed/moderncircle32/800/600",
    inStock: false,
    description: "Hand-glazed serving bowl in sage tones.",
  },
];
